development:
  adapter: postgresql
  encoding: utf8
  database: enpronto_development
  pool: 5
  username: frankjwu
  password:

test: &TEST
  adapter: postgresql
  encoding: utf8
  database: enpronto_test
  pool: 5
  username: frankjwu
  password:

production:
  adapter: postgresql
  encoding: utf8
  database: enpronto_production
  pool: 5
  username: frankjwu
  password:
